### ISSUE TITLE
Spot extraction can break when drift-corrected ROIs table contains floating-point bounds

### ISSUE THREAD

**Issue by vreuter** [gerlichlab/looptrace#18]
When the table of regions of interest (ROIs) contains bounding coordinates that are decimals / floating-point values, the spot extraction step (`extract_spots.py`, after spot detection) can fail because the floating-point values are used as indices to build `slice`s, which is illegal since those indices must be integers.

```shell
Traceback (most recent call last):
  File "/looptrace/bin/cli/extract_spots.py", line 30, in <module>
    S.gen_roi_imgs_inmem()
  File "/opt/conda/lib/python3.10/site-packages/looptrace-0.2-py3.10.egg/looptrace/SpotPicker.py", line 372, in gen_roi_imgs_inmem
  File "/opt/conda/lib/python3.10/site-packages/looptrace-0.2-py3.10.egg/looptrace/SpotPicker.py", line 337, in extract_single_roi_img_inmem
TypeError: slice indices must be integers or None or have an __index__ method
```

**Comment by vreuter** [comment]
Running with 'dog' as the spot detection algorithm for dataset 5853 seems to work, supporting the notion that this is likely solved.
