### ISSUE TITLE
Spot extraction zip and cleanup breaks

### ISSUE THREAD

**Issue by vreuter** [gerlichlab/looptrace#19]
The call to `image_io.zip_folder` in `SpotPicker.gen_roi_imgs_inmem` can break.
```shell
Traceback (most recent call last):
  File "/looptrace/bin/cli/extract_spots.py", line 30, in <module>
    S.gen_roi_imgs_inmem()
  File "/opt/conda/lib/python3.10/site-packages/looptrace-0.2-py3.10.egg/looptrace/SpotPicker.py", line 390, in gen_roi_imgs_inmem
  File "/opt/conda/lib/python3.10/site-packages/looptrace-0.2-py3.10.egg/looptrace/image_io.py", line 379, in zip_folder
  File "/opt/conda/lib/python3.10/shutil.py", line 731, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/opt/conda/lib/python3.10/shutil.py", line 729, in rmtree
    os.rmdir(path)
OSError: [Errno 39] Directory not empty: '/home/experiment/Tracing09_TS_oPool01_03/spot_images_dir'
```

**Comment by vreuter** [comment]
Running with 'dog' as the spot detection algorithm for dataset 5853 seems to work, supporting the notion that this is likely solved.

**Comment by vreuter** [comment]
hasn't come up in quite some time
