### ISSUE TITLE
With `UniversalProximityPermission`, `minimumPixelLikeSeparation` is incorrectly required

### ISSUE THREAD

**Issue by vreuter** [gerlichlab/looptrace#308]
```
Traceback (most recent call last):
  File "/looptrace/bin/cli/run_processing_pipeline.py", line 348, in <module>
    main(sys.argv[1:])
  File "/looptrace/bin/cli/run_processing_pipeline.py", line 343, in main
    pipeline.run(start_point=opts.start_point, stop_after=opts.stop_after)
  File "/opt/conda/lib/python3.10/site-packages/pypiper/pipeline.py", line 319, in run
    stage.run()
  File "/opt/conda/lib/python3.10/site-packages/pypiper/stage.py", line 56, in run
    self(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/pypiper/stage.py", line 64, in __call__
    self.f(*args, **kwargs)
  File "/looptrace/bin/cli/detect_spots.py", line 101, in workflow
    return S.rois_from_spots(outfile=outfile)
  File "/opt/conda/lib/python3.10/site-packages/looptrace/SpotPicker.py", line 528, in rois_from_spots
    params = self.detection_parameters
  File "/opt/conda/lib/python3.10/site-packages/looptrace/SpotPicker.py", line 427, in detection_parameters
    minimum_distance_between=self.image_handler.minimum_spot_separation,
  File "/opt/conda/lib/python3.10/site-packages/looptrace/ImageHandler.py", line 201, in minimum_spot_separation
    return get_minimum_regional_spot_separation(self.config)
  File "/opt/conda/lib/python3.10/site-packages/looptrace/configuration.py", line 24, in get_minimum_regional_spot_separation
    return get_region_grouping_config(conf_data)[MINIMUM_SPOT_SEPARATION_KEY]
KeyError: 'minimumPixelLikeSeparation'
```

**Comment by vreuter** [comment]
Experienced by @TLSteinacker
