### ISSUE TITLE
Spot detection preview (and maybe spot detection itself) can't work with basic napari dependency

### ISSUE THREAD

**Issue by vreuter** [gerlichlab/looptrace#7]
It appears we may need `napari[all]` as a dependency, rather than simply `napari`, as spot detection (which uses `napari`) hits a snag otherwise:
```
Traceback (most recent call last):
  File "/users/vincent.reuter/code/looptrace/bin/cli/detect_spots_preview.py", line 23, in <module>
    S.rois_from_spots(preview_pos=preview_pos)
  File "/opt/conda/lib/python3.10/site-packages/looptrace-0.2-py3.10.egg/looptrace/SpotPicker.py", line 116, in rois_from_spots
  File "/opt/conda/lib/python3.10/site-packages/looptrace-0.2-py3.10.egg/looptrace/image_processing_functions.py", line 491, in napari_view
  File "/opt/conda/lib/python3.10/site-packages/napari/_lazy.py", line 48, in __getattr__
    submod = import_module(
  File "/opt/conda/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/conda/lib/python3.10/site-packages/napari/view_layers.py", line 20, in <module>
    from napari.components.dims import Dims
  File "/opt/conda/lib/python3.10/site-packages/napari/components/__init__.py", line 17, in <module>
    from .camera import Camera
  File "/opt/conda/lib/python3.10/site-packages/napari/components/camera.py", line 7, in <module>
    from ..utils.events import EventedModel
  File "/opt/conda/lib/python3.10/site-packages/napari/utils/__init__.py", line 2, in <module>
    from .colormaps import Colormap
  File "/opt/conda/lib/python3.10/site-packages/napari/utils/colormaps/__init__.py", line 2, in <module>
    from .colormap import Colormap
  File "/opt/conda/lib/python3.10/site-packages/napari/utils/colormaps/colormap.py", line 7, in <module>
    from napari.utils.color import ColorArray
  File "/opt/conda/lib/python3.10/site-packages/napari/utils/color.py", line 7, in <module>
    from napari.utils.colormaps.standardize_color import transform_color
  File "/opt/conda/lib/python3.10/site-packages/napari/utils/colormaps/standardize_color.py", line 27, in <module>
    from vispy.color import ColorArray, get_color_dict, get_color_names
  File "/opt/conda/lib/python3.10/site-packages/vispy/__init__.py", line 27, in <module>
    from .util import config, set_log_level, keys, sys_info  # noqa
  File "/opt/conda/lib/python3.10/site-packages/vispy/util/__init__.py", line 14, in <module>
    from . import fonts       # noqa
  File "/opt/conda/lib/python3.10/site-packages/vispy/util/fonts/__init__.py", line 13, in <module>
    from ._triage import _load_glyph, list_fonts  # noqa, analysis:ignore
  File "/opt/conda/lib/python3.10/site-packages/vispy/util/fonts/_triage.py", line 11, in <module>
    from ._freetype import _load_glyph
  File "/opt/conda/lib/python3.10/site-packages/vispy/util/fonts/_freetype.py", line 16, in <module>
    from ...ext.fontconfig import find_font
  File "/opt/conda/lib/python3.10/site-packages/vispy/ext/fontconfig.py", line 12, in <module>
    raise ImportError('fontconfig not found')
ImportError: fontconfig not found
```

**Comment by vreuter** [comment]
Likely solved here: https://github.com/gerlichlab/looptrace/commit/d71f92da176421b2ac56c1a2650f2fedeeeef130

**Comment by vreuter** [comment]
Still not solved, may need to install a system library, per this related issue in another project: https://github.com/vispy/vispy/issues/1556#issuecomment-1379480239

**Comment by vreuter** [comment]
To avoid costly cycles of build-push-pull, we need a way to trigger this error quickly, ideally running the Docker container locallz or on the beefy lab Linux machine.

**Comment by vreuter** [comment]
> To avoid costly cycles of build-push-pull, we need a way to trigger this error quickly, ideally running the Docker container locallz or on the beefy lab Linux machine.

```python
from napari.utils.colormaps.standardize_color import transform_color
```

**Comment by vreuter** [comment]
> > To avoid costly cycles of build-push-pull, we need a way to trigger this error quickly, ideally running the Docker container locallz or on the beefy lab Linux machine.
> 
> ```python
> from napari.utils.colormaps.standardize_color import transform_color
> ```

This produces:
```shell
WARNING: Could not load OpenGL library.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.10/site-packages/napari/utils/__init__.py", line 2, in <module>
    from .colormaps import Colormap
  File "/opt/conda/lib/python3.10/site-packages/napari/utils/colormaps/__init__.py", line 2, in <module>
    from .colormap import Colormap
  File "/opt/conda/lib/python3.10/site-packages/napari/utils/colormaps/colormap.py", line 7, in <module>
    from napari.utils.color import ColorArray
  File "/opt/conda/lib/python3.10/site-packages/napari/utils/color.py", line 7, in <module>
    from napari.utils.colormaps.standardize_color import transform_color
  File "/opt/conda/lib/python3.10/site-packages/napari/utils/colormaps/standardize_color.py", line 27, in <module>
    from vispy.color import ColorArray, get_color_dict, get_color_names
  File "/opt/conda/lib/python3.10/site-packages/vispy/color/__init__.py", line 12, in <module>
    from .colormap import (Colormap, BaseColormap,  # noqa
  File "/opt/conda/lib/python3.10/site-packages/vispy/color/colormap.py", line 14, in <module>
    import vispy.gloo
  File "/opt/conda/lib/python3.10/site-packages/vispy/gloo/__init__.py", line 47, in <module>
    from . import gl  # noqa
  File "/opt/conda/lib/python3.10/site-packages/vispy/gloo/gl/__init__.py", line 230, in <module>
    from . import es2 as default_backend  # noqa
  File "/opt/conda/lib/python3.10/site-packages/vispy/gloo/gl/es2.py", line 48, in <module>
    raise OSError('GL ES 2.0 library not found')
OSError: GL ES 2.0 library not found
```

**Comment by vreuter** [comment]
In addition to some OS/platform/system specific packages -- see [here](https://github.com/vispy/vispy/issues/1556#issuecomment-1379480239) and [here](https://github.com/napari/napari/issues/1457#issuecomment-752667286) -- it appears we need `pip install pyqt5`, otherwise this will happen (or is at least possible):
```shell
Traceback (most recent call last):
  File "/home/vr/venvs/looptrace/lib/python3.10/site-packages/napari/_qt/__init__.py", line 9, in <module>
    from qtpy import API_NAME, QtCore
  File "/home/vr/venvs/looptrace/lib/python3.10/site-packages/qtpy/__init__.py", line 259, in <module>
    raise QtBindingsNotFoundError from None
qtpy.QtBindingsNotFoundError: No Qt bindings could be found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vr/code/looptrace/./bin/cli/detect_spots_preview.py", line 23, in <module>
    S.rois_from_spots(preview_pos=preview_pos)
  File "/home/vr/venvs/looptrace/lib/python3.10/site-packages/looptrace/SpotPicker.py", line 116, in rois_from_spots
    ip.napari_view(np.stack([filt_img, img, orig]), axes = 'CZYX', points=roi_points, downscale=1, name = ['DoG', 'Subtracted', 'Original'])
  File "/home/vr/venvs/looptrace/lib/python3.10/site-packages/looptrace/image_processing_functions.py", line 491, in napari_view
    viewer = napari.view_image(img, channel_axis = channel_axis, name=name)
  File "/home/vr/venvs/looptrace/lib/python3.10/site-packages/napari/view_layers.py", line 179, in view_image
    return _make_viewer_then('add_image', args, kwargs)[0]
  File "/home/vr/venvs/looptrace/lib/python3.10/site-packages/napari/view_layers.py", line 157, in _make_viewer_then
    viewer = Viewer(**vkwargs)
  File "/home/vr/venvs/looptrace/lib/python3.10/site-packages/napari/viewer.py", line 63, in __init__
    from .window import Window
  File "/home/vr/venvs/looptrace/lib/python3.10/site-packages/napari/window.py", line 14, in <module>
    from ._qt import Window
  File "/home/vr/venvs/looptrace/lib/python3.10/site-packages/napari/_qt/__init__.py", line 12, in <module>
    raise type(e)(
TypeError: QtBindingsNotFoundError.__init__() takes 1 positional argument but 2 were given
```

**Comment by vreuter** [comment]
After some testing with @TLSteinacker , this appears to be an issue related to trying to run a `napari`-dependent call (more specifically, something which requires interactive graphics windows) on Ubuntu through WSL2, at least in my local configuration of it if not more generally as well. Closing this ticket for now and reopening a more specific one, since it's much lower priority given the feasibility of running one of these programs or function calls on macOS (again, from testing with @TLSteinacker )
